language: java
before_install:
- sudo rm /usr/local/bin/docker-compose
- sudo curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname
  -s`-`uname -m` -o /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn clean
- mvn install -Dmaven.javadoc.skip=false -B -V
- ls -l
- docker build --build-arg JAR_FILE=./target/app.jar -t $DOCKER_USERNAME/se234-lab10-backend  .
- docker push  $DOCKER_USERNAME/se234-lab10-backend
- docker pull  $DOCKER_USERNAME/se234-lab10-client
script:
- docker-compose -H $DOCKER_HOST up 
after_success:
- docker ps
env:
  global:
  - secure: ODXiRWkgGvAkler8MJeCk35Dm1i/rwO5OICSFNmpzRH/aKJM0kz2pC0oeg5G+v9SeU5Vy6tBd8U89PZffkqGLlu+Ur0p8PpB4y6hwf9GohtyRLkv5SQencO+kpyK0c6eauAqxmYqsveDXqr9DBvkL6EpfLKimhZ+Uc3Zv2+V23UcAOG0F1dnERVZDNEILnFZjrjg9zV0lQ5fXQmbPFlutBdRGj6CO1c7zDrrgHZeBBH2ZgdeJqaCdz5v28ZR4ukrmf9gMzX1WlNTRT4XSrhUGKbkpBDaAJb6TS5KevFDu+Nf6kBJvUlzgDg8ymaKiVxMq1//yhfY8okuJGQFW/NJ/0npV8atyrdcKcI6EQZSy4vvIB5gUqDw5+kwEDiqCdRtP5dBOYB8OG1ShUbnzlyl2Kkx6/uXchyNk+OlOdG0P+6ODaVPfEkCxcqMvksq13pm6apjMWVY+Cm4DHG9V0/jr1aAYVchlNOtofguAs5D9L6QCex+hPIqhUZL5WXmIzwtQ3T35D+vmti3CAy0VgwPOO4HNp5BWOU3zh9N+hYxBllM+hLEn+KahQb6xW1Gy1yR9BCVgTi184Lm1O2e+i/gi3+bxwKpgo2+v2fZ44/C4538Mi1huYmWViEGb2+HFoP1lhve3eJvCACD9giMqAb4F8Gq1BFf8YsaamXGGHM2r+Q=
  - secure: STr++EG3aWJnPNlRc9BcieK35Q1F3ZV8OfaiFF64HkKhE3Y+mYuUTF+DPcp7RLxwawEWYAIshNtRy1GqbFEjRwPtoV9hSQlrHlKlpuC3PeEqUkcGwK9LA+zKaGiQy72/CwWr6UxxN5EKVh0VxaKtfEl9fldOGWElFoQ3bxwOx0oQ8T5fZpRjLB4X2QtOEz14EuKghdsjGXzpVYK7DY3bGVLgOcWQvfvrGI0LFwZR7oY1hGRsmiwaOh7dhECK5GRveBeKGbxjEG7HtUuLoR70+ACUrzjdIxinHnvLiXts4RfLdAAgfmbMwWlkdvkLmGoT3Qy3R2uPrrL4W73t+2gagZ9mX6bIVFN9syGVr5ZRX98fgSv5J+jsK8zLiHn2FaJV7GXD4OVIwyBoQtJmDJZW/BmpGvxM5aOIlKjJBY35d79qsJqp+QhJxi6mSQIH6fXT2vxbFqruWSorllLhjjDpXyvo0a1nsCjmB6WlvYwo+b93OV62xR2+JoZF6alM6PpqeDWEZaTF5+nb2veUNsR95dTGXQcB5GCny9M9LdtZxxjeM4srpu3S4/uuE5jFLAyPU+VZPr9kfEsexi8EuzG3gIQxmQR1ySb/HPM4+s5xlvKq6hLYxuRslT5G+O1b8kg4jAjmbigVHKWmT/J6zN2xbYQIsSIvZdGIy4TD5H1gQoE=
  - secure: qTXo+UVQ/J0FOuTrfE+0akoaYhJXhvRBEzZiOGoT3rn9Fgnqegb2rpEEoHDGcsCNsX9gCYgc3TPRc+0edydmWngafPwaUJcTeDX7ogrvVH5KfZov1lxCcp88D0hP4y9eUUvRT8W7G0YfuprQCSyBO2semJ4tP1ZCpmLXLVeShE0O6Gns06SD7IvFyZHScW5cVC73FVkoRhBHU1CO794W0gdo6QdUhuDbBePwBPNqcNR6p8uhKQgyJpPX4Ii/bRsJXgURnpLWIvs43oaDE+T3nf/Iy9TnWEiWUA8ItoT+ReEW2q2vHzeL4TfBbPmVpxvxd4yZ9yGQbmTSbHzmQrz7xw6bEjT1D1p98XcoFGxpPU4lw/QQpZ1iFp2gysCO95XIX8NZgOSc2YfBnRXx4eifbTMYMtvGrSMyIfGcxpyaQcKUQRKqOVC6B5g1fRdRrgdXAktMSigp+vuito7ucQBd240cjq1vjUt5NUEQE1hNPonE7VtCn86hVwKsF0uhqV08XxlVGqF2PgzFhPm9oWJdpNCag34kRi4/7OGZKcoSI4/shZD9koUyu7nvc7roDKtAdUsMZCjGhU6zd7pA1zt90ZimfYuhM4NiLM8YZki7xu24BY3u6c0KA2I5SEO+Tzzvhh+bjAn61HycmmJnBRPxYwuLB7eWyHNXEjJutjZwFxM=
